const MOCK = window.CostCatcherData;

const nav = [
  {label:'대시보드',page:'dashboard',icon:'dashboard'},
  {section:'원가 분석'},{label:'식자재 가격 분석',page:'ingredient',icon:'chart',sub:true},{label:'상세 분석',page:'detail',icon:'search',sub:true},
  {section:'메뉴·레시피'},{label:'레시피 관리',page:'recipes',icon:'recipe',sub:true},{label:'메뉴 원가 분석',page:'menu-cost',icon:'cost',sub:true},
  {section:'매장 관리'},{label:'매장 리스트',page:'stores',icon:'store',sub:true},{label:'가맹점 관리',page:'franchise',icon:'users',sub:true},
  {section:'브리핑 & 알림'},{label:'브리핑 기록',page:'briefings',icon:'brief',sub:true},{label:'알림 센터',page:'alerts',icon:'bell',sub:true},
  {section:'마이페이지'},{label:'회원 정보',page:'profile',icon:'user',sub:true},{label:'설정',page:'settings',icon:'settings',sub:true},{label:'요금제',page:'plans',icon:'card',sub:true},
  {section:'체험'},{label:'비회원 화면',page:'guest',icon:'preview',sub:true}
];

const state={page:'dashboard',ingredient:'cabbage',granularity:'daily',period:'4주',horizon:3,evidenceHorizon:0,evidenceGranularity:'daily',recipe:'kimchi',store:'전체 매장'};
const $=(selector,root=document)=>root.querySelector(selector);
const $$=(selector,root=document)=>[...root.querySelectorAll(selector)];
const money=n=>Number(n).toLocaleString('ko-KR')+'원';
const iconSvg=name=>{const paths={dashboard:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',chart:'<path d="M4 19V5M4 19h16M7 15l4-5 3 2 5-6"/>',search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',recipe:'<path d="M6 3v18M10 6h10M10 12h10M10 18h7"/>',cost:'<circle cx="12" cy="12" r="9"/><path d="M15 8.5c-.7-.6-1.5-.9-2.6-.9-1.5 0-2.6.7-2.6 1.8 0 2.8 5.7 1.3 5.7 4.3 0 1.2-1.1 2-2.8 2-1.2 0-2.2-.4-3-1M12.5 5.5v13"/>',store:'<path d="M3 9h18l-2-5H5L3 9Z"/><path d="M5 9v11h14V9M9 20v-6h6v6"/>',users:'<circle cx="9" cy="8" r="3"/><path d="M3 20c0-4 2-6 6-6s6 2 6 6M16 5c2 0 3 1 3 3s-1 3-3 3M17 14c3 0 4 2 4 5"/>',brief:'<path d="M5 3h14v18H5zM8 7h8M8 11h8M8 15h5"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>',user:'<circle cx="12" cy="8" r="4"/><path d="M4 21c0-5 3-8 8-8s8 3 8 8"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/>',card:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 10h18"/>',preview:'<path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.5"/>'};return `<svg viewBox="0 0 24 24" aria-hidden="true">${paths[name]||paths.preview}</svg>`};

function init(){
  $('#mainNav').innerHTML=nav.map(item=>item.section?`<div class="nav-label">${item.section}</div>`:`<button class="nav-item ${item.sub?'sub':''}" data-page="${item.page}"><span class="nav-icon">${iconSvg(item.icon)}</span>${item.label}</button>`).join('');
  bindGlobal();
  route(location.hash.replace('#/','')||'dashboard',false);
  seedChat();
}

function bindGlobal(){
  document.addEventListener('click',e=>{
    const pageTarget=e.target.closest('[data-page]');
    if(pageTarget){route(pageTarget.dataset.page);$('#sidebar').classList.remove('open');}
    const company=e.target.closest('[data-company]');
    if(company){$('#companyButton').innerHTML=`${company.dataset.company} <span>⌄</span>`;$('#companyDropdown').classList.remove('open');toast('조직이 변경되었습니다.');}
  });
  $('#companyButton').onclick=e=>{e.stopPropagation();$('#companyDropdown').classList.toggle('open');};
  document.addEventListener('click',()=>$('#companyDropdown').classList.remove('open'));
  $('#sidebarOpen').onclick=()=>$('#sidebar').classList.add('open');
  $('#sidebarClose').onclick=()=>$('#sidebar').classList.remove('open');
  $('#notificationButton').onclick=()=>{route('alerts');toast('읽지 않은 알림 3건을 불러왔습니다.');};
  $('#helpButton').onclick=()=>openModal('원가 캣쳐 도움말','대시보드에서 시장 신호를 확인하고, 상세 분석에서 근거 데이터를 검토한 다음 메뉴 원가 영향을 확인하세요. 오른쪽 아래 AI 챗봇에서도 현재 화면의 데이터를 질문할 수 있습니다.');
  $('#chatLauncher').onclick=openChat;$('#chatMinimize').onclick=closeChat;
  $('#chatForm').onsubmit=sendChat;
  $('#modalClose').onclick=closeModal;$('#modalBackdrop').onclick=e=>{if(e.target===e.currentTarget)closeModal();};
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();closeChat();$('#sidebar').classList.remove('open');}});
  window.addEventListener('hashchange',()=>route(location.hash.replace('#/','')||'dashboard',false));
}

function route(page,push=true){
  document.body.classList.add('route-loading');
  state.page=page;
  if(push)location.hash=`/${page}`;
  $$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===page));
  const found=nav.find(n=>n.page===page);const subtitles={dashboard:'오늘의 식자재 동향과 원가 위험 신호를 확인하세요.',ingredient:'품목별 실제 가격과 향후 예측 구간을 비교합니다.',detail:'가격 변화의 근거를 데이터별로 확인합니다.',recipes:'등록 메뉴와 식재료 사용량을 관리합니다.','menu-cost':'시장 변동이 메뉴 원가에 미치는 영향을 확인합니다.',stores:'여러 매장의 원가 위험 현황을 통합 관리합니다.',franchise:'가맹점별 위험 품목과 담당 현황을 관리합니다.',briefings:'생성된 원가 브리핑 기록을 확인합니다.',alerts:'새로운 위험 신호와 변경 사항을 확인합니다.',profile:'회원 및 조직 정보를 관리합니다.',settings:'알림과 서비스 사용 환경을 설정합니다.',plans:'사업 규모에 맞는 플랜을 비교합니다.',guest:'로그인 전 공개되는 서비스 소개 화면입니다.'};$('#pageTitle').textContent=found?.label||'원가 캣쳐';$('#pageSubtitle').textContent=subtitles[page]||'';$('#breadcrumb').textContent=`원가 캣쳐 / ${found?.label||''}`;const pageStyle=$('#pageStyle');if(pageStyle)pageStyle.href=`css/pages/${page}.css`;
  const renderer=pages[page]||pages.dashboard;$('#appMain').classList.remove('page-enter');$('#appMain').innerHTML=renderer();void $('#appMain').offsetWidth;$('#appMain').classList.add('page-enter');$('#appMain').focus({preventScroll:true});bindPage(page);setTimeout(()=>document.body.classList.remove('route-loading'),360);
}

const priceCards=()=>MOCK.ingredients.map(i=>`<article class="card price-card" data-ingredient="${i.id}" tabindex="0"><div class="photo-slot" aria-label="${i.name} 사진 자리">사진</div><div><h3>${i.name}</h3><div class="price-value">${money(i.price).replace('원','')}<small>${i.unit}</small></div><span class="change ${i.change>0?'up':'down'}">${i.change>0?'▲':'▼'} ${Math.abs(i.change)}% &nbsp;<small>전일 대비</small></span></div><span class="status-badge status-${i.status}">${i.label}</span></article>`).join('');
const selectOptions=()=>MOCK.ingredients.map(i=>`<option value="${i.id}" ${state.ingredient===i.id?'selected':''}>${i.name}</option>`).join('');
const forecastPoint=(id=state.ingredient,horizon=state.horizon)=>{const chart=MOCK.charts[id]||MOCK.charts.cabbage;const index=state.granularity==='daily'?Math.min(Math.max(horizon,1),chart.forecast.length-1):Math.min(horizon*2,chart.forecast.length-1);const current=chart.actual.at(-1);const price=chart.forecast[index];const probability=Math.max(52,Math.min(91,({cabbage:72,'green-onion':59,onion:44,radish:61,garlic:39}[id]||60)+(state.granularity==='daily'?Math.ceil(index/2):horizon*2)));return{price,low:chart.low[index],high:chart.high[index],probability,change:(price-current)/current*100,index}};
const horizonLabel=value=>state.granularity==='daily'?`${value}일 후`:state.granularity==='monthly'?'1개월 후':`${value}주 후`;
function forecastMetrics(){const f=forecastPoint();return `<div><span>${horizonLabel(state.horizon)} 예상 가격</span><strong>${money(f.price)}/kg</strong><small>현재 대비 <b class="${f.change>=0?'negative':'positive'}">${f.change>=0?'+':''}${f.change.toFixed(1)}%</b></small></div><div><span>가격 상승 가능성</span><strong>${f.probability}%</strong><small>AI 종합 예측 신뢰도</small></div><div><span>예측 가격 범위</span><strong>${money(f.low)} ~ ${money(f.high)}</strong><small>90% 예측 구간</small></div>`}
function forecastPanel(){return `<section class="forecast-panel" aria-label="가격 예측 정보"><div class="forecast-guide"><span class="forecast-guide-icon">↗</span><span><strong id="forecastHoverLabel">${horizonLabel(state.horizon)} 예측값을 표시 중입니다.</strong> 예측 점선 위에 마우스를 움직이면 날짜별 정보가 아래에 표시됩니다.</span></div><div class="forecast-metrics" id="forecastMetrics">${forecastMetrics()}</div></section>`}
function granularityControl(){return `<label class="granularity-control"><span>조회 단위</span><select class="filter-control granularity-filter" aria-label="그래프 조회 단위"><option value="daily" ${state.granularity==='daily'?'selected':''}>일별</option><option value="weekly" ${state.granularity==='weekly'?'selected':''}>주별</option><option value="monthly" ${state.granularity==='monthly'?'selected':''}>월별</option></select></label>`}
const periodOptions={daily:['4주','8주','12주'],weekly:['3개월','6개월','1년'],monthly:['1년','3년','5년']};

const pages={
  dashboard:()=>`<div class="content"><section><div class="section-head"><div><h2>오늘의 주요 식자재 도매가</h2><p>2026.08.13 06:00 기준 · 가락시장 상품 기준</p></div><div class="section-actions"><select class="filter-control" id="dateFilter"><option>2026.08.13 (목)</option><option>2026.08.12 (수)</option></select><select class="filter-control" id="storeFilter"><option>전체 매장</option>${MOCK.stores.slice(0,4).map(s=>`<option>${s.name}</option>`).join('')}</select></div></div><div class="cards price-grid">${priceCards()}</div></section>
  <section class="dashboard-middle"><article class="card chart-card"><div class="section-head"><div><h2>식자재 가격 추이 & 예측</h2><div class="legend"><span><i></i>실제 가격</span><span><i class="forecast"></i>예측 가격</span><span><i class="range"></i>예측 범위</span></div></div><div class="chart-toolbar"><select class="filter-control ingredient-filter">${selectOptions()}</select><select class="filter-control period-filter"><option>4주</option><option>8주</option><option>12주</option></select></div></div><div class="chart-wrap" id="mainChart"></div>${forecastPanel()}</article>${evidenceCard()}</section>
  <section><div class="section-head"><div><h2>내 메뉴 원가 영향 TOP 3</h2><p><span id="impactIngredient">배추</span> 가격 예측이 등록 메뉴 원가에 미치는 영향</p></div><button class="text-link" data-page="menu-cost">전체 메뉴 분석 →</button></div><div class="cards cost-grid">${impactCards()}</div></section></div>`,
  ingredient:()=>`<div class="content"><div class="page-intro"><div><h2>식자재 가격 분석</h2><p>주요 품목의 현재 가격과 향후 변동 신호를 한 화면에서 비교합니다.</p></div><select class="filter-control period-filter"><option>4주</option><option>8주</option><option>12주</option></select></div><div class="cards price-grid">${priceCards()}</div><article class="card chart-card"><div class="section-head"><div><h2>품목별 가격 전망</h2><p>실선은 실제 가격, 점선은 AI 예측값입니다.</p></div><select class="filter-control ingredient-filter">${selectOptions()}</select></div><div class="chart-wrap" id="mainChart"></div>${forecastPanel()}</article></div>`,
  detail:()=>detailPage(),
  recipes:()=>recipePage(false),
  'menu-cost':()=>recipePage(true),
  stores:()=>storesPage('매장 리스트'),
  franchise:()=>storesPage('가맹점 관리'),
  briefings:()=>briefPage(false),
  alerts:()=>briefPage(true),
  profile:()=>settingsPage('profile'),
  settings:()=>settingsPage('settings'),
  plans:()=>plansPage(),
  guest:()=>guestPage()
};

function evidenceCard(){return `<article class="card evidence-card" id="evidenceCard" aria-live="polite"><div class="section-head"><div><h2>금일 산출 근거 요약</h2><p>AI가 선택 시점의 위험 신호에 반영한 핵심 데이터</p></div><div class="evidence-head-actions"><span class="evidence-selected-label" id="evidenceSelectedLabel">오늘 기준</span><button class="text-link" data-page="detail">상세 보기 →</button></div></div><section class="evidence-block"><h3 class="evidence-block-title"><span>a.</span> 생산량 기준 근거표</h3><div id="productionEvidence">${productionTable()}</div></section><section class="evidence-block"><h3 class="evidence-block-title"><span>b.</span> 근거 정량 데이터 · 기상</h3><div id="weatherEvidence">${weatherTable()}</div></section><div class="ai-summary" id="evidenceExplanation"><strong>관련 데이터 설명</strong>최근 주산지의 강수량 증가와 고온이 동시에 관측되고 있으며, 생산량 및 출하량이 평년 대비 감소한 상태입니다. 이 데이터가 배추 가격 상승 위험의 주요 근거로 반영되었습니다.</div></article>`}
const evidenceDays=(horizon,granularity)=>granularity==='daily'?horizon:granularity==='weekly'?horizon*7:30;
function productionTable(horizon=0,granularity='daily'){let rows=MOCK.production;if(horizon>0){const days=evidenceDays(horizon,granularity),derived=[['생산량',Math.max(68000,82300-days*220),91000,87600,'t'],['재배면적',Math.max(13800,15240-days*18),16310,15980,'ha'],['출하량',Math.max(64000,78500-days*260),88900,83100,'t']];rows=derived.map(([metric,current,normal,previous,unit])=>({metric,current:`${current.toLocaleString()}${unit}`,normal:`${normal.toLocaleString()}${unit}`,previous:`${previous.toLocaleString()}${unit}`,change:`${((current-normal)/normal*100).toFixed(1)}%`}))}return `<div class="table-wrap"><table class="data-table"><thead><tr><th>지표</th><th>${horizon?'예상':'현재'}</th><th>평년</th><th>전년 동기</th><th>변화율</th></tr></thead><tbody>${rows.map(r=>`<tr><td><strong>${r.metric}</strong></td><td>${r.current}</td><td>${r.normal}</td><td>${r.previous}</td><td class="negative">▼ ${r.change.replace('-','')}</td></tr>`).join('')}</tbody></table></div>`}
function weatherTable(horizon=0,granularity='daily'){let rows=MOCK.weather;if(horizon>0){const focus=evidenceDays(horizon,granularity),start=Math.max(1,focus-2);rows=Array.from({length:5},(_,i)=>{const day=start+i,temp=27.2+Math.min(day,18)*.18,rain=10+(day%4)*10.4,humidity=68+(day%5)*4,risk=temp>=29.5||rain>=38?'위험':temp>=28.2||rain>=25?'주의':'안정';return{date:`D+${day}`,temp:`${temp.toFixed(1)}℃`,rain:`${rain.toFixed(1)}mm`,humidity:`${humidity}%`,risk}})}return `<div class="table-wrap"><table class="data-table"><thead><tr><th>날짜</th><th>평균기온</th><th>강수량</th><th>습도</th><th>위험도</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.date}</td><td>${r.temp}</td><td class="${parseFloat(r.rain)>30?'negative':''}">${r.rain}</td><td>${r.humidity}</td><td><span class="status-badge status-${r.risk==='위험'?'danger':r.risk==='주의'?'warning':'success'}">${r.risk}</span></td></tr>`).join('')}</tbody></table></div>`}
function updateEvidencePanel(){const card=$('#evidenceCard');if(!card)return;const label=horizonLabel(state.evidenceHorizon),days=evidenceDays(state.evidenceHorizon,state.evidenceGranularity);$('#evidenceSelectedLabel').textContent=`${label} 예측 근거`;$('#productionEvidence').innerHTML=productionTable(state.evidenceHorizon,state.evidenceGranularity);$('#weatherEvidence').innerHTML=weatherTable(state.evidenceHorizon,state.evidenceGranularity);$('#evidenceExplanation').innerHTML=`<strong>${label} AI 근거 설명</strong>선택 시점까지 누적된 고온·강수 위험과 출하량 감소 추세를 반영했습니다. 현재 시나리오에서는 ${days}일 누적 영향으로 공급 여력이 낮아져 가격 상승 위험이 확대되는 것으로 분석됩니다.`;card.classList.remove('evidence-updated');void card.offsetWidth;card.classList.add('evidence-updated')}
function impactCards(){return MOCK.menuImpacts.map(m=>`<article class="card menu-impact"><div class="menu-top"><div class="menu-photo-slot" aria-label="${m.name} 사진 자리">사진</div><div><h3>${m.name}</h3><span class="ingredient-use">${m.use}</span></div><div class="impact-delta">+${money(m.delta)}<small>▲ ${m.rate}%</small></div></div><div class="cost-flow"><div><span>현재 원가</span><strong>${money(m.current)}</strong></div><b>→</b><div><span>예상 원가 (3주 후)</span><strong>${money(m.future)}</strong></div></div><div class="impact-footer"><span class="status-badge status-${m.status}">영향 ${m.level}</span><button class="text-link" data-page="menu-cost">원가 상세 보기 →</button></div></article>`).join('')}

function detailPage(){const metricIcon=n=>`<span class="metric-icon">${iconSvg(n)}</span>`;return `<div class="content"><div class="page-intro"><div><h2>${getIngredient().name} 상세 분석</h2><p>가격 예측 결과와 판단 근거를 데이터 출처별로 확인합니다.</p></div><div class="section-actions"><select class="filter-control ingredient-filter">${selectOptions()}</select><button class="button secondary" id="downloadBrief">브리핑 저장</button></div></div><div class="cards kpi-grid"><article class="card kpi-card"><span>3주 후 가격 상승 가능성</span><strong style="color:var(--danger)">78%</strong><small>지난주 대비 +9%p</small></article><article class="card kpi-card"><span>위험도</span><strong>높음</strong><small>AI 종합 위험 점수 82/100</small></article><article class="card kpi-card"><span>예상 영향 기간</span><strong>3주 후</strong><small>2026.09.03 전후</small></article><article class="card kpi-card"><span>3주 후 예상 가격</span><strong>3,790원</strong><small>현재 대비 +10.8%</small></article></div><div class="detail-grid"><article class="card chart-card"><div class="section-head"><div><h2>가격 추이 & 예측 범위</h2><p>90% 예측 구간을 함께 표시합니다.</p></div><select class="filter-control period-filter"><option>4주</option><option>8주</option></select></div><div class="chart-wrap" id="mainChart"></div></article><div class="metric-list"><article class="card metric">${metricIcon('chart')}<div><span>생산량</span><strong>82,300t</strong></div><b>▼ 9.6%</b></article><article class="card metric">${metricIcon('brief')}<div><span>출하량</span><strong>78,500t</strong></div><b>▼ 11.7%</b></article><article class="card metric">${metricIcon('store')}<div><span>재배면적</span><strong>15,240ha</strong></div><b>▼ 6.6%</b></article><article class="card metric">${metricIcon('bell')}<div><span>기상 위험</span><strong>고온·다우</strong></div><b>위험</b></article></div></div><div class="detail-grid" style="margin-top:14px"><article class="card evidence-card"><div class="section-head"><div><h2>근거 데이터</h2><p>생산·출하 및 기상 관측 요약</p></div></div>${productionTable()}<div style="height:12px"></div>${weatherTable()}</article><article class="card evidence-card"><div class="section-head"><div><h2>정책·수급 신호</h2><p>비정형 데이터 분석 결과</p></div></div><div class="metric-list"><div class="modal-detail"><strong>수급</strong><p>가락시장 반입량이 7일 이동평균 대비 12.4% 감소했습니다.</p></div><div class="modal-detail"><strong>정책</strong><p>정부 비축 물량 방출 검토가 보도됐으나 단기 공급 효과는 제한적으로 반영했습니다.</p></div></div><div class="ai-summary"><strong>AI 종합 해석</strong>고온과 집중호우가 생육을 늦추고 출하량 감소로 이어지는 패턴이 관찰됩니다. 재배면적 감소 추세까지 겹쳐 3주 후 가격 상승 가능성을 78%로 산정했습니다.</div></article></div></div>`}

function recipePage(costOnly){const active=MOCK.recipes.find(r=>r.id===state.recipe)||MOCK.recipes[0];return `<div class="content"><div class="page-intro"><div><h2>${costOnly?'메뉴 원가 분석':'레시피 관리'}</h2><p>레시피별 식재료 구성과 시장 전망을 반영한 예상 원가를 관리합니다.</p></div><button class="button primary" id="addRecipe">+ 메뉴 추가</button></div><div class="recipe-layout"><aside class="card list-panel"><input class="search-input" id="recipeSearch" placeholder="메뉴 검색"> <div id="recipeList">${recipeList(active.id)}</div></aside><article class="card detail-panel" id="recipeDetail">${recipeDetail(active,costOnly)}</article></div></div>`}
function recipeList(activeId){return MOCK.recipes.map(r=>`<button class="recipe-item ${r.id===activeId?'active':''}" data-recipe="${r.id}"><span class="recipe-photo-slot">사진</span><span><strong>${r.name}</strong><small>현재 원가 ${money(r.current)}</small></span></button>`).join('')}
function recipeDetail(r,costOnly=false){return `<div class="recipe-header"><div><h3>${r.name}</h3><p>${r.servings} 기준 레시피 · 마지막 수정 2026.08.12</p></div><button class="button ghost" id="editRecipe">레시피 수정</button></div><div class="cards kpi-grid"><article class="card kpi-card"><span>현재 메뉴 원가</span><strong>${money(r.current)}</strong><small>원가율 31.2%</small></article><article class="card kpi-card"><span>3주 후 예상 원가</span><strong style="color:var(--danger)">${money(r.future)}</strong><small>+${money(r.future-r.current)} 상승</small></article><article class="card kpi-card"><span>판매가</span><strong>8,500원</strong><small>매장 평균</small></article><article class="card kpi-card"><span>예상 원가율</span><strong>33.8%</strong><small>+2.6%p</small></article></div><div class="section-head"><div><h2>식재료 구성</h2><p>현재 매입 단가 기준</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>식재료</th><th>사용량</th><th>현재 매입 단가</th><th>가격 전망</th></tr></thead><tbody>${r.items.map((it,i)=>`<tr><td><strong>${it[0]}</strong></td><td>${it[1]}</td><td>${it[2]}</td><td><span class="status-badge status-${i===0?'danger':'success'}">${i===0?'상승':'안정'}</span></td></tr>`).join('')}</tbody></table></div>${costOnly?'<div class="ai-summary"><strong>AI 원가 제안</strong>배추 사용량이 전체 예상 원가 상승분의 72%를 차지합니다. 한시적 대체 규격 검토 또는 3주분 선발주를 권장합니다.</div>':''}`}

function storesPage(title){return `<div class="content"><div class="page-intro"><div><h2>${title}</h2><p>전체 매장의 위험 품목과 담당 현황을 통합 관리합니다.</p></div><button class="button primary" id="addStore">+ 가맹점 추가</button></div><div class="cards store-summary"><article class="card kpi-card"><span>전체 매장</span><strong>14</strong><small>직영 4 · 가맹 10</small></article><article class="card kpi-card"><span>위험 품목 보유 매장</span><strong style="color:var(--danger)">9</strong><small>전일 대비 +2</small></article><article class="card kpi-card"><span>평균 예상 원가 상승</span><strong>6.8%</strong><small>3주 전망 기준</small></article></div><article class="card store-table-card"><div class="section-head"><div><h2>매장 현황</h2><p>행을 선택하면 매장별 관리 품목을 확인할 수 있습니다.</p></div><select class="filter-control" id="regionFilter"><option>전체 지역</option><option>서울</option><option>경기</option></select></div><div class="table-wrap"><table class="data-table"><thead><tr><th>매장명</th><th>지역</th><th>관리 품목</th><th>현재 위험 품목</th><th>담당자</th><th>상태</th></tr></thead><tbody id="storeRows">${MOCK.stores.map(s=>storeRow(s)).join('')}</tbody></table></div></article></div>`}
function storeRow(s){return `<tr class="store-row" data-store="${s.name}" tabindex="0"><td class="store-name">${s.name}</td><td>${s.region}</td><td>${s.items}</td><td class="${s.risks==='없음'?'positive':'negative'}">${s.risks}</td><td>${s.manager}</td><td><span class="status-dot"></span>${s.state}</td></tr>`}
function briefPage(alerts){const items=alerts?[...MOCK.briefings,{date:'2026.08.10',type:'시스템',title:'매장 데이터 동기화 완료',summary:'14개 매장의 매입 단가가 업데이트되었습니다.',body:'마지막 동기화 시각은 08:30입니다.'}]:MOCK.briefings;return `<div class="content"><div class="page-intro"><div><h2>${alerts?'알림 센터':'브리핑 기록'}</h2><p>${alerts?'시장 변화와 매장 원가에 영향을 주는 알림을 확인합니다.':'AI가 생성한 일간·주간 원가 브리핑을 모아 봅니다.'}</p></div><button class="button secondary" id="markRead">${alerts?'모두 읽음':'주간 브리핑 생성'}</button></div><div class="timeline">${items.map((b,i)=>`<div class="timeline-item"><span class="timeline-dot"></span><article class="card brief-card" data-brief="${i}"><span class="brief-date">${b.date} · ${b.type}</span><h3>${b.title}</h3><p>${b.summary}</p></article></div>`).join('')}</div></div>`}

function settingsPage(selected){return `<div class="content"><div class="page-intro"><div><h2>${selected==='profile'?'회원 정보':'설정'}</h2><p>계정, 회사 정보와 서비스 알림 방식을 관리합니다.</p></div></div><div class="settings-layout"><aside class="card settings-menu">${['회원 정보','비밀번호 변경','회사 정보','알림 설정','가맹점 설정','사용자 권한','요금제 / 결제','로그아웃'].map((x,i)=>`<button class="${i===(selected==='profile'?0:3)?'active':''}" data-setting="${i}">${x}</button>`).join('')}</aside><article class="card settings-panel" id="settingsPanel">${selected==='profile'?profilePanel():notificationPanel()}</article></div></div>`}
function profilePanel(){return `<div class="recipe-header"><div><h3>회원 정보</h3><p>서비스에서 사용하는 기본 프로필입니다.</p></div><button class="button ghost" id="saveSettings">저장</button></div><div class="setting-row"><div><span>이름</span><small>원가캣쳐</small></div><button class="button ghost">변경</button></div><div class="setting-row"><div><span>이메일</span><small>admin@catcherfood.co.kr</small></div><span class="status-badge status-success">인증 완료</span></div><div class="setting-row"><div><span>회사 / 조직</span><small>(주)캣쳐푸드 · 관리자</small></div><button class="button ghost">관리</button></div>`}
function notificationPanel(){return `<div class="recipe-header"><div><h3>알림 설정</h3><p>받고 싶은 위험 신호와 전달 채널을 선택하세요.</p></div><button class="button primary" id="saveSettings">저장</button></div>${[['위험 품목 즉시 알림','위험도가 주의에서 위험으로 바뀌면 알림',true],['주간 원가 브리핑','매주 월요일 오전 9시 이메일 발송',true],['메뉴 원가 영향 알림','예상 원가 상승률이 5%를 넘으면 알림',true],['정책·수급 뉴스','관련 정책 및 공급 이슈 업데이트',false]].map(r=>`<div class="setting-row"><div><span>${r[0]}</span><small>${r[1]}</small></div><button class="toggle ${r[2]?'on':''}" aria-label="${r[0]} 켜기/끄기"></button></div>`).join('')}`}

function plansPage(){return `<div class="content"><div class="page-intro" style="justify-content:center;text-align:center"><div><h2>사업 규모에 맞는 원가 인텔리전스</h2><p>모든 가격과 기능은 시안용 Mock Data이며 언제든 변경할 수 있습니다.</p></div></div><div class="cards pricing-grid">${MOCK.plans.map(p=>`<article class="card price-plan ${p.featured?'recommended':''}">${p.featured?'<span class="recommend-label">가장 많이 선택</span>':''}<h3>${p.name}</h3><p>${p.desc}</p><div class="plan-price">${p.price}<small>${p.price.includes('월')?' / VAT 별도':''}</small></div><ul class="feature-list">${p.features.map(f=>`<li>${f}</li>`).join('')}</ul><button class="button ${p.featured?'primary':'ghost'}" data-plan="${p.name}">${p.price==='별도 문의'?'도입 문의':'플랜 선택'}</button></article>`).join('')}</div></div>`}
function guestPage(){return `<div class="content"><section class="guest-hero"><div><span class="status-badge status-success">식자재 원가 조기경보</span><h2>원가 변동을<br>가격보다 먼저 포착하세요.</h2><p>기상·작황·생산·출하·수급·정책 데이터를 AI가 함께 분석해, 사업자의 메뉴 원가에 미칠 영향까지 연결합니다.</p><div class="market-mini"><span>배추 <b class="negative">▲ 4.2%</b></span><span>대파 <b class="negative">▲ 1.8%</b></span><span>양파 <b>→ 안정</b></span></div><button class="button primary" id="freeStart">무료로 시작하기</button></div><div class="preview-locked"><div class="fake-chart chart-wrap" id="guestChart"></div><div class="lock-overlay"><div><strong>AI 예측과 상세 근거를 확인하려면<br>로그인하세요.</strong><button class="button primary" id="loginPreview">로그인하고 확인</button></div></div></div></section><div class="section-head" style="margin-top:28px"><div><h2>데이터에서 대응까지, 하나의 흐름으로</h2><p>대시보드 → 상세 근거 → 메뉴 원가 영향</p></div></div><div class="cards cost-grid"><article class="card kpi-card"><span>01 · 시장 감지</span><strong>이상 신호 포착</strong><small>7개 데이터 영역을 함께 분석</small></article><article class="card kpi-card"><span>02 · 근거 확인</span><strong>설명 가능한 예측</strong><small>가격 변화의 이유를 정량 데이터로 확인</small></article><article class="card kpi-card"><span>03 · 사업 대응</span><strong>메뉴 원가 영향</strong><small>등록 메뉴와 매장까지 영향 연결</small></article></div></div>`}

function updateForecastSelection(){
  const target=$('#mainChart'),svg=target?.querySelector('svg');if(!svg)return;
  svg.querySelector('.forecast-selection')?.remove();
}

function bindPage(page){
  const chartCard=$('#mainChart')?.closest('.chart-card');if(chartCard&&!chartCard.querySelector('.granularity-control')){const toolbar=chartCard.querySelector('.chart-toolbar')||chartCard.querySelector('.section-head');toolbar?.insertAdjacentHTML('beforeend',granularityControl());}
  $$('.period-filter').forEach(el=>{const options=periodOptions[state.granularity];el.innerHTML=options.map(value=>`<option ${value===state.period?'selected':''}>${value}</option>`).join('');});
  if($('#mainChart')&&!$('.forecast-panel')&&!$('#mainChart').classList.contains('fake-chart'))$('#mainChart').insertAdjacentHTML('afterend',forecastPanel());
  $$('.granularity-filter').forEach(el=>el.onchange=()=>{state.granularity=el.value;state.period=periodOptions[state.granularity][0];state.horizon=state.granularity==='monthly'?4:3;route(page,false);toast(`${el.options[el.selectedIndex].text} 가격 추이로 변경했습니다.`);});
  $$('.ingredient-filter').forEach(el=>el.onchange=()=>{state.ingredient=el.value;renderChart($('#mainChart'),state.ingredient);if(page==='detail'){route('detail',false);return}if($('#forecastMetrics'))$('#forecastMetrics').innerHTML=forecastMetrics();updateForecastSelection();});
  $$('.period-filter').forEach(el=>el.onchange=()=>{state.period=el.value;renderChart($('#mainChart'),state.ingredient);toast(`${el.value} 기간으로 조회했습니다.`);});
  $$('.price-card').forEach(el=>{el.onclick=()=>{state.ingredient=el.dataset.ingredient;route(page==='dashboard'?'detail':'ingredient',false);};el.onkeydown=e=>{if(e.key==='Enter')el.click();};});
  if($('#mainChart')){renderChart($('#mainChart'),state.ingredient);updateForecastSelection();}
  if($('#guestChart'))renderChart($('#guestChart'),'cabbage',true);
  $$('.tab').forEach(t=>t.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');$('#evidenceBody').innerHTML=t.dataset.evidence==='weather'?weatherTable():productionTable();});
  $('#storeFilter')?.addEventListener('change',e=>toast(`${e.target.value} 기준으로 원가 영향을 다시 계산했습니다.`));
  $('#dateFilter')?.addEventListener('change',e=>toast(`${e.target.value} 데이터를 불러왔습니다.`));
  $('#downloadBrief')?.addEventListener('click',()=>toast('브리핑이 내 기록에 저장되었습니다.'));
  $$('.recipe-item').forEach(b=>b.onclick=()=>{state.recipe=b.dataset.recipe;const r=MOCK.recipes.find(x=>x.id===state.recipe);$('#recipeList').innerHTML=recipeList(state.recipe);$('#recipeDetail').innerHTML=recipeDetail(r,page==='menu-cost');bindPage(page);});
  $('#recipeSearch')?.addEventListener('input',e=>{$$('.recipe-item').forEach(x=>x.style.display=x.textContent.includes(e.target.value)?'flex':'none');});
  $('#addRecipe')?.addEventListener('click',()=>openModal('새 메뉴 추가','시안에서는 저장하지 않습니다. 실제 제품에서는 메뉴명, 판매가, 제공량을 입력한 뒤 식재료와 사용량을 등록하는 흐름으로 연결됩니다.',true));
  $('#editRecipe')?.addEventListener('click',()=>toast('레시피 편집 모드로 전환했습니다.'));
  $$('.store-row').forEach(row=>row.onclick=()=>{state.store=row.dataset.store;const s=MOCK.stores.find(x=>x.name===state.store);openModal(`${s.name} 원가 현황`,`${s.region} · 담당자 ${s.manager}<br><br>현재 위험 품목은 <strong>${s.risks}</strong>입니다. 배추 관련 등록 메뉴 4개의 예상 원가가 평균 7.2% 상승할 것으로 보입니다.`);});
  $('#regionFilter')?.addEventListener('change',e=>{$('#storeRows').innerHTML=MOCK.stores.filter(s=>e.target.value==='전체 지역'||s.region.startsWith(e.target.value)).map(storeRow).join('');bindPage(page);});
  $('#addStore')?.addEventListener('click',()=>openModal('가맹점 추가','매장 기본 정보와 담당자를 등록하는 UI입니다. 프로토타입에서는 입력값이 저장되지 않습니다.',true));
  $$('.brief-card').forEach((b,i)=>b.onclick=()=>{const item=MOCK.briefings[i]||MOCK.briefings[0];openModal(item.title,`<span class="status-badge status-warning">${item.type}</span><p>${item.body}</p><div class="modal-detail">예상 영향: 배추 사용 메뉴 평균 원가 +7.4%<br>권장 대응: 2~3주 물량 발주 시점 검토</div>`);});
  $('#markRead')?.addEventListener('click',()=>toast(page==='alerts'?'모든 알림을 읽음 처리했습니다.':'새 주간 브리핑을 생성했습니다.'));
  $$('.settings-menu button').forEach(b=>b.onclick=()=>{if(Number(b.dataset.setting)===7){location.href='login.html';return;}$$('.settings-menu button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#settingsPanel').innerHTML=Number(b.dataset.setting)===3?notificationPanel():profilePanel();bindPage(page);});
  $$('.toggle').forEach(b=>b.onclick=()=>b.classList.toggle('on'));$('#saveSettings')?.addEventListener('click',()=>toast('설정이 저장되었습니다.'));
  $$('[data-plan]').forEach(b=>b.onclick=()=>openModal(`${b.dataset.plan} 플랜`,`선택하신 플랜은 시안용입니다. 실제 결제는 진행되지 않습니다.`));
  $('#freeStart')?.addEventListener('click',()=>location.href='signup.html');
  $('#loginPreview')?.addEventListener('click',()=>location.href='login.html');
}

function renderChart(target,id='cabbage',decorative=false){if(!target)return;const data=MOCK.charts[id]||MOCK.charts.cabbage;const actual=data.actual,forecast=data.forecast;const all=[...actual,...forecast,...data.low,...data.high];const min=Math.floor((Math.min(...all)-150)/500)*500,max=Math.ceil((Math.max(...all)+150)/500)*500;const W=760,H=290,p={l:56,r:18,t:18,b:38};const count=actual.length+forecast.length-1;const x=i=>p.l+i*(W-p.l-p.r)/(count-1),y=v=>p.t+(max-v)*(H-p.t-p.b)/(max-min);const actualPts=actual.map((v,i)=>`${x(i)},${y(v)}`).join(' ');const offset=actual.length-1;const forecastPts=forecast.map((v,i)=>`${x(offset+i)},${y(v)}`).join(' ');const area=[...data.high.map((v,i)=>`${x(offset+i)},${y(v)}`),...data.low.map((v,i)=>`${x(offset+data.low.length-1-i)},${y(data.low[data.low.length-1-i])}`)].join(' ');const steps=5;let grid='';for(let i=0;i<steps;i++){const v=max-(max-min)*i/(steps-1),yy=y(v);grid+=`<line class="grid-line" x1="${p.l}" x2="${W-p.r}" y1="${yy}" y2="${yy}"/><text class="axis-label" x="${p.l-9}" y="${yy+4}" text-anchor="end">${Math.round(v).toLocaleString()}</text>`;}const labels=['4/22','4/29','5/6','5/13','5/20','5/27','6/3','6/10','6/17'];const labelMarkup=labels.map((l,i)=>{const xx=p.l+i*(W-p.l-p.r)/(labels.length-1);return `<text class="axis-label" x="${xx}" y="${H-11}" text-anchor="middle">${l}</text>`}).join('');target.innerHTML=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${getIngredient(id).name} 실제 및 예측 가격 그래프">${grid}<polygon class="range-area" points="${area}"/><line class="today-line" x1="${x(offset)}" x2="${x(offset)}" y1="${p.t}" y2="${H-p.b}"/><polyline class="actual-line" points="${actualPts}"/><polyline class="forecast-line" points="${forecastPts}"/><circle class="chart-point" cx="${x(offset)}" cy="${y(actual.at(-1))}" r="5"/>${labelMarkup}<text class="axis-label" x="${x(offset)}" y="${H-25}" text-anchor="middle" style="font-weight:800;fill:#185c4a">오늘</text>${actual.map((v,i)=>`<circle class="hit-point" data-value="${v}" cx="${x(i)}" cy="${y(v)}" r="9" fill="transparent"/>`).join('')}</svg><div class="chart-tooltip"></div>`;if(!decorative){$$('.hit-point',target).forEach(dot=>{dot.onmouseenter=e=>{const tt=$('.chart-tooltip',target);tt.style.display='block';tt.style.left=`${Math.min(e.offsetX+8,target.clientWidth-100)}px`;tt.style.top=`${Math.max(e.offsetY-48,0)}px`;tt.innerHTML=`실제 도매가<strong>${money(dot.dataset.value)}/kg</strong>`;};dot.onmouseleave=()=>$('.chart-tooltip',target).style.display='none';});}}
const average=values=>Math.round(values.reduce((sum,value)=>sum+value,0)/values.length);
function buildChartSeries(source,granularity='daily'){
  if(granularity==='weekly'){
    const actual=[];for(let i=0;i<source.actual.length;i+=5)actual.push(average(source.actual.slice(i,i+5)));actual[actual.length-1]=source.actual.at(-1);
    const points=[0,2,4,6,8];
    return{actual,forecast:points.map(i=>source.forecast[i]),low:points.map(i=>i===0?source.actual.at(-1):source.low[i]),high:points.map(i=>i===0?source.actual.at(-1):source.high[i]),labels:['4월 4주','5월 1주','5월 2주','5월 3주','오늘','1주 후','2주 후','3주 후','4주 후']};
  }
  if(granularity==='monthly'){
    return{actual:[average(source.actual.slice(0,12)),average(source.actual.slice(12,24)),source.actual.at(-1)],forecast:[source.actual.at(-1),source.forecast.at(-1)],low:[source.actual.at(-1),source.low.at(-1)],high:[source.actual.at(-1),source.high.at(-1)],labels:['3월','4월','5월 현재','6월 예측']};
  }
  return{actual:[...source.actual],forecast:[...source.forecast],low:[...source.low],high:[...source.high],labels:['4/22','4/29','5/6','5/13','5/20','5/27','6/3','6/10','6/17']};
}
const renderChartBase=renderChart;
function attachForecastInteractions(target,series){
  const svg=target.querySelector('svg');if(!svg)return;
  svg.querySelector('.forecast-interactions')?.remove();
  const W=760,H=290,p={l:56,r:18,t:18,b:38},all=[...series.actual,...series.forecast,...series.low,...series.high],min=Math.floor((Math.min(...all)-150)/500)*500,max=Math.ceil((Math.max(...all)+150)/500)*500,count=series.actual.length+series.forecast.length-1,offset=series.actual.length-1,x=i=>p.l+i*(W-p.l-p.r)/(count-1),y=value=>p.t+(max-value)*(H-p.t-p.b)/(max-min),points=state.granularity==='daily'?series.forecast.slice(1).map((_,index)=>({h:index+1,i:index+1})):state.granularity==='weekly'?[{h:1,i:1},{h:2,i:2},{h:3,i:3},{h:4,i:4}]:[{h:4,i:1}],ns='http://www.w3.org/2000/svg',group=document.createElementNS(ns,'g');group.setAttribute('class','forecast-interactions');
  points.forEach(point=>{
    const item=document.createElementNS(ns,'g'),cx=x(offset+point.i),cy=y(series.forecast[point.i]);
    item.setAttribute('class',`forecast-event-point ${state.granularity==='daily'?'daily-hover-zone':''}`);item.setAttribute('tabindex','0');item.setAttribute('role','button');item.setAttribute('aria-label',`${horizonLabel(point.h)} 예상 가격 ${money(series.forecast[point.i])}`);
    item.innerHTML=`<circle class="forecast-point-dot" cx="${cx}" cy="${cy}" r="4"/><circle class="forecast-point-hit" cx="${cx}" cy="${cy}" r="15"/>`;
    const preview=()=>{state.horizon=point.h;if($('#forecastMetrics'))$('#forecastMetrics').innerHTML=forecastMetrics();const label=$('#forecastHoverLabel');if(label)label.textContent=`${horizonLabel(point.h)} 예측값을 표시 중입니다.`;updateForecastSelection();};
    const commit=()=>{preview();state.evidenceHorizon=point.h;state.evidenceGranularity=state.granularity;updateEvidencePanel();};
    item.addEventListener('mouseenter',preview);item.addEventListener('focus',preview);item.addEventListener('click',commit);group.append(item);
  });
  svg.append(group);
}
renderChart=function(target,id='cabbage',decorative=false){
  if(!target)return;
  const source=MOCK.charts[id]||MOCK.charts.cabbage,series=buildChartSeries(source,state.granularity),previous=MOCK.charts[id];
  MOCK.charts[id]=series;renderChartBase(target,id,decorative);MOCK.charts[id]=previous;
  const labels=[...target.querySelectorAll('svg text.axis-label')].filter(el=>el.getAttribute('y')==='279');
  labels.forEach((el,index)=>{if(index<series.labels.length){el.textContent=series.labels[index];el.setAttribute('x',String(56+index*(760-56-18)/Math.max(1,series.labels.length-1)));el.style.display=''}else el.style.display='none'});
  const svg=target.querySelector('svg');if(svg)svg.setAttribute('aria-label',`${getIngredient(id).name} ${state.granularity==='daily'?'일별':state.granularity==='weekly'?'주별':'월별'} 실제 및 예측 가격 그래프`);if(!decorative)attachForecastInteractions(target,series);
};
function getIngredient(id=state.ingredient){return MOCK.ingredients.find(i=>i.id===id)||MOCK.ingredients[0]}

function seedChat(){addChat('ai','안녕하세요! 원가 캣쳐 AI입니다.\n\n식자재 가격, 원가 영향, 메뉴 분석 등 무엇이든 물어보세요.');}
function openChat(){$('#chatPanel').classList.add('open');document.body.classList.add('chat-open');$('#chatPanel').setAttribute('aria-hidden','false');$('#chatLauncher').style.display='none';setTimeout(()=>$('#chatInput').focus(),150)}
function closeChat(){$('#chatPanel').classList.remove('open');document.body.classList.remove('chat-open');$('#chatPanel').setAttribute('aria-hidden','true');$('#chatLauncher').style.display='block'}
function addChat(role,text){const row=document.createElement('div');row.className=`chat-row ${role}`;const time=new Date().toLocaleTimeString('ko-KR',{hour:'2-digit',minute:'2-digit'});row.innerHTML=role==='ai'?`<div class="chat-mascot mascot-crop" role="img" aria-label="원가 캣쳐 고양이 마스코트"></div><div><div class="bubble">${text}</div><span class="chat-time">${time}</span></div>`:`<div><div class="bubble">${text}</div><span class="chat-time">${time}</span></div>`;$('#chatMessages').append(row);$('#chatMessages').scrollTop=$('#chatMessages').scrollHeight}
function sendChat(e){e.preventDefault();const input=$('#chatInput'),text=input.value.trim();if(!text)return;addChat('user',text);input.value='';setTimeout(()=>{const answer=text.includes('배추')||text.includes('이유')?'현재 배추는 3주 후 가격 상승 가능성이 78%로 높게 예측되고 있어요.\n\n주요 근거는 다음과 같습니다.\n• 주산지 강수량 증가\n• 고온으로 인한 생육 지연\n• 출하량 감소\n• 재배면적 감소 추세\n\n더 자세한 근거는 ‘상세 분석’ 페이지에서 확인해보세요.':text.includes('메뉴')||text.includes('원가')?'배추 가격 상승 시 김치찌개의 예상 원가는 1,000원에서 1,092원으로 약 9.2% 오를 수 있어요. 메뉴 원가 분석에서 다른 메뉴도 비교할 수 있습니다.':'현재 화면의 Mock Data를 기준으로 답변하고 있어요. 배추 가격 전망, 메뉴 원가 영향, 위험 신호의 근거를 질문해보세요.';addChat('ai',answer)},650)}
function toast(message){const el=document.createElement('div');el.className='toast';el.textContent=message;$('#toastRegion').append(el);setTimeout(()=>el.remove(),2600)}
function openModal(title,body,form=false){$('#modalContent').innerHTML=`<h2 id="modalTitle">${title}</h2><p>${body}</p>${form?'<input class="search-input" placeholder="이름 또는 정보를 입력하세요"><div style="display:flex;justify-content:flex-end;gap:8px;margin-top:14px"><button class="button ghost" onclick="document.querySelector(\'#modalClose\').click()">취소</button><button class="button primary" onclick="document.querySelector(\'#modalClose\').click();window.setTimeout(()=>document.querySelector(\'#toastRegion\').insertAdjacentHTML(\'beforeend\',\'<div class=toast>프로토타입에서는 저장되지 않습니다.</div>\'),50)">확인</button></div>':''}`;$('#modalBackdrop').classList.add('open');$('#modalBackdrop').setAttribute('aria-hidden','false')}
function closeModal(){$('#modalBackdrop').classList.remove('open');$('#modalBackdrop').setAttribute('aria-hidden','true')}

init();
